### Get all
GET http://localhost:3000/events

### Create
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "event name",
  "description": "event description",
  "date": "2020-01-01T00:00:00",
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}

### Get one
GET http://localhost:3000/events/{{ eventId }}

### Update
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
  "name": "event name",
  "description": "event descriptionn",
  "date": "2020-01-01T00:00:00",
  "price": 100
}

### Delete
DELETE http://localhost:3000/events/{{ eventId }}


### Spot

### Get all
GET http://localhost:3000/events/{{ eventId }}/spots

### Create
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json

{
  "name": "A1"
}

###
@spotId = {{ createSpot.response.body.id }}

## Get one
GET http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}

### Update
PATCH http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}
Content-Type: application/json

{
  "name": "A2"
}

### Delete
DELETE http://localhost:3000/events/{{ eventId }}/spots/{{ spotId }}